services:
  postgres:
    image: quay.io/tembo/pgmq-pg:latest
    container_name: sdpe-postgres-local
    environment:
      POSTGRES_USER: sdpe
      POSTGRES_PASSWORD: sdpe
      POSTGRES_DB: sdpe
    ports:
      - '5432:5432'
    volumes:
      - sdpe_pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  sdpe_pg_data:
